<?xml version="1.0" encoding="utf-8"?><Database Name="Ceylone_Moter_DB" Class="DBchartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-O4D1A34;Initial Catalog=Ceylone_Moter_DB;Integrated Security=True" SettingsObjectName="Sales_and_Inventory_System__Gadgets_Shop_.Properties.Settings" SettingsPropertyName="Ceylone_Moter_DBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.lowQuantity" Member="lowQuantities">
    <Type Name="lowQuantity">
      <Column Name="ProductName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>