#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales_and_Inventory_System__Gadgets_Shop_
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ceylone_Moter_DB")]
	public partial class MonthSalesChartDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MonthSalesChartDataContext() : 
				base(global::Sales_and_Inventory_System__Gadgets_Shop_.Properties.Settings.Default.Ceylone_Moter_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MonthSalesChartDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonthSalesChartDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonthSalesChartDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MonthSalesChartDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MonthSalesview> MonthSalesviews
		{
			get
			{
				return this.GetTable<MonthSalesview>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonthSalesview")]
	public partial class MonthSalesview
	{
		
		private string _MonthName;
		
		private System.Nullable<double> _TotalSale;
		
		private System.Nullable<double> _Total_Due_PymentSales;
		
		public MonthSalesview()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthName", DbType="NVarChar(30)")]
		public string MonthName
		{
			get
			{
				return this._MonthName;
			}
			set
			{
				if ((this._MonthName != value))
				{
					this._MonthName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSale", DbType="Float")]
		public System.Nullable<double> TotalSale
		{
			get
			{
				return this._TotalSale;
			}
			set
			{
				if ((this._TotalSale != value))
				{
					this._TotalSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Due_PymentSales", DbType="Float")]
		public System.Nullable<double> Total_Due_PymentSales
		{
			get
			{
				return this._Total_Due_PymentSales;
			}
			set
			{
				if ((this._Total_Due_PymentSales != value))
				{
					this._Total_Due_PymentSales = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
